apiVersion: apps/v1
kind: Deployment
metadata:
  name: santa-deployment
spec:
  selector:
    matchLabels:
      app: santa
  replicas: 2 
  template:
    metadata:
      labels:
        app: santa
    spec:
      containers:
        - name: santa
          image: javaexpress/santa:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
---
apiVersion: v1 
kind: Service 
metadata: 
  name: santa-ssvc
spec:
  selector:
    app: santa
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080
  type: LoadBalancer 
